### ISSUE TITLE
Force react modules

### ISSUE THREAD

**Issue by nuvolarmobileteam** [forcedotcom/SalesforceMobileSDK-Package#108]
Hello guys,

We are planning to build a react native app that connects to Salesforce. For now this will be a very simple one so we do not need most of the modules included in the whole package.

I was wondering if there is any way to create a new `forcereact` app specifying the modules to be installed, SalesforceSDKCore only for instance.

If this can not be done using `forcereact` would it be possible to do it manually.

Thank you very much in advance,

Albert

**Comment by bhariharan** [comment]
@nuvolarmobileteam Nope, this is not possible. The `SalesforceReact` library depends on `SmartSync`, which depends on `SmartStore`, which depends on `SalesforceSDKCore`. The reason for this is because we have bridges for all our modules in `SalesforceReact`. Also, this forum is reserved for known issues/bugs with our code. For other queries, please use our [developer community](https://plus.google.com/u/1/communities/114225252149514546445).

**Comment by nuvolarmobileteam** [comment]
Hi @bhariharan 
Thanks for the answer. Sorry for not posting the question in the right place.
