### ISSUE TITLE
oauth.logout() is not redirecting to differed login page

### ISSUE THREAD

**Issue by rsiuli001** [forcedotcom/SalesforceMobileSDK-Package#202]
Hi,

I have created a react-native project using 'forcereact' package. The Project is working as expected. I have created a differed login page and the login flow is also working perfectly. But when i'm trying to call oauth.logout() to logout the user from the app, its not working as expected.

Expectation: After the logout the app should go back to the login page.
Current Behaviour: The app is working as expected if the differed login is not in place. After implementing the differed login, there is a blank screen after the user clicks on logout. As there is no callback for iOS in oauth.logout() I'm not sure when the logout is getting success. 

How can i implement the logout() functionality properly, so that when the user clicks on logout, on successful logout the user is presented with differed login page in iOS. 

[package.json.txt](https://github.com/forcedotcom/SalesforceMobileSDK-Package/files/4744740/package.json.txt)

**Comment by bhariharan** [comment]
@rsiuli001 Is this on `iOS` or `Android`?

**Comment by rsiuli001** [comment]
This is on iOS.

**Comment by wmathurin** [comment]
It looks like deferred login + logout from react native will leave you in a bad place.
We have create a story/bug in our internal issue tracking system.
Thanks for reporting the issue.

**Comment by rsiuli001** [comment]
One more query, If i have an access_token from Azure, is there any way we can reuse the same token in SDK? For us Azure authentication is implemented in Salesforce.

**Comment by rsiuli001** [comment]
Is there any example app or documentation for using JWT bearer flow for SDK?

**Comment by ygavrylenko** [comment]
You wouldn't use JWT Bearer Flow directly from SDK, you have to build some piece of middleware that would retrieve SF access token after you got token from your Azure IdP, this middleware would check that user is authenticated agains Azure and would retrieve SF token using server to server JWT Bearer Flow. 
However it's only needed if you want to access multiple services directly form your app (with access token obtain directly from Azure) otherwise you'd just configure Azure IdP in Salesforce and would get access token from SDK.

**Comment by rsiuli001** [comment]
Yes, We want multiple services to be obtained from our app, thats why we need this architecture. So, once the middleware is created and the SF access token is obtained, how should i pass the token to SDK?

**Comment by ygavrylenko** [comment]
Well JTW Bearer Flow would request access token from SF (no refresh token for this flow) and you would give the access token to your app. However you are out of standard Mobile SDK functionality, since SDK establishes connection using User-Agent flow directly to Salesforce. So I can't assess which parts of SDK you can reuse in this case, I guess you can maybe set credentials in SDK manually but again, we are out of standard so it's custom development and risk connected to this.
Alternatively you can request external resources from Salesforce (using SF like middleware to access resources outside) using Salesforce access token but that would mean you have to log-in to Saleforce.

**Comment by rsiuli001** [comment]
Thank you all for you response. I have one more query related to login.
Is there any event that fires if the user clicks on the back button of the login page? If not how should i handle the event in our app?

![Simulator Screen Shot - iPhone 11 - 2020-06-25 at 12 41 56](https://user-images.githubusercontent.com/62182948/85673604-afb51b00-b6e1-11ea-921f-b3bc1cea680b.png)

**Comment by rsiuli001** [comment]
@wmathurin @ygavrylenko  @bhariharan is there any way to track the above event? Please let me know.

**Comment by wmathurin** [comment]
We will update this issue when progress is made.

**Comment by wmathurin** [comment]
In the next release (8.2), you will be able to pass a callback to oauth.logout().
That way you will know logout completes. See https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/pull/191
We also added a basic template that demonstrates deferred login (and logout callback): https://github.com/forcedotcom/SalesforceMobileSDK-Templates/pull/278
